on:
    pull_request:
      types: [opened, reopened, ready_for_review, synchronize]
    issue_comment:
      types: [created]
    push:
      branches: [main, staging, dev]
  
jobs:
    pr_agent_job:
        if: ${{ github.event.sender.type != 'Bot' }}
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
            contents: write
        name: Run PR Agent on pull requests and respond to comments
        steps:
            - name: PR Agent action step
              id: pragent
              uses: Codium-ai/pr-agent@main
              env:
                OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                PR_REVIEWER.REQUIRE_TESTS_REVIEW: "false"
                PR_CODE_SUGGESTIONS.NUM_CODE_SUGGESTIONS: 6 
